#!/bin/sh
#
# /etc/rc.d/gpm: start/stop the GPM console mouse service
#

. /etc/conf.d/gpm
. /etc/rc.subr

NAME="GPM console mouse service"
PROG=/usr/sbin/gpm
OPTS="-m $MDEVICE -t $PROTOCOL $GPMOPTS"
PID=$(pidof -o %PPID $PROG)

case $1 in
	start)
		msg "Starting GPM console mouse service..."
		if [ -z "$PID" ]; then
			$PROG $OPTS
			eval_stat
		else
			stat_skip
		fi
		;;
	stop)
		msg "Stopping GPM console mouse service..."
		if [ ! -z "$PID" ]; then
			kill $PID &>/dev/null
			eval_stat
		else
			stat_skip
		fi
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		if [ "$PID" ]; then
			echo "$NAME is running with pid: $PID"
		else
			echo "$NAME is not running."
		fi
		;;
	*)
		echo "usage: $0 [start|stop|restart|status]"
		;;
esac

# End of file
