#!/bin/sh
#
# /etc/rc.d/lxdm: start/stop lxdm daemon
#

. /etc/rc.subr

NAME="LXDM"
PROG=/usr/sbin/lxdm-binary
PIDFILE=/var/run/lxdm.pid

case $1 in
	start)
		msg "Starting $NAME..."
		start_daemon /usr/sbin/lxdm -d
		eval_stat
		;;
	stop)
		msg "Stopping $NAME..."
		stop_daemon /usr/sbin/lxdm
		eval_stat
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		status_daemon $PROG
		;;
	*)
		echo "usage: $0 [start|stop|restart|status]"
		;;
esac

# End of file
