#!/bin/sh

if [ "$UID" != "0" ];then
	echo "$(basename $0) need to run as root!"
	exit 1
fi

SYSUSERS_DIR=/etc/sysusers.d
SYSUSERS_FILE=/etc/sysusers

for file in $SYSUSERS_FILE $(ls $SYSUSERS_DIR/*.conf 2>/dev/null); do
	[ ! -f $file ] && continue
	while read uid gid mode dir junk; do
		# Ignore comments and blank lines
		case "$uid" in
			""|\#*) continue ;;
		esac
		if [ -e "$dir" ]; then
			if [ "$uid" != '-' ]; then
				getent passwd $uid >/dev/null
				if [[ "$?" = 0 ]]; then
					chown "$uid" "$dir"
				fi
			fi
			if [ "$gid" != '-' ]; then
				getent group $gid >/dev/null
				if [[ "$?" = 0 ]]; then
					chgrp "$gid" "$dir"
				fi
			fi
			if [ "$mode" != '-' ]; then
				chmod "$mode" "$dir"
			fi
		fi
	done < "$file"
done

exit $?
